name: myenv
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - asgiref=3.8.1=py39haa95532_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - attrs=24.2.0=py39haa95532_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - bcrypt=3.2.0=py39h2bbff1b_1
  - blas=1.0=mkl
  - blosc=1.21.3=h6c2663c_0
  - boost-cpp=1.82.0=h59b6b97_2
  - bottleneck=1.3.7=py39h9128911_0
  - branca=0.6.0=py39haa95532_0
  - brotli=1.0.9=h2bbff1b_8
  - brotli-bin=1.0.9=h2bbff1b_8
  - brotli-python=1.0.9=py39hd77b12b_8
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2024.9.24=haa95532_0
  - cairo=1.16.0=hc68a040_5
  - certifi=2024.8.30=py39haa95532_0
  - cffi=1.17.1=py39h827c3e9_0
  - cfitsio=3.470=h2bbff1b_7
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.1.7=py39haa95532_0
  - click-plugins=1.1.1=pyhd3eb1b0_0
  - cligj=0.7.2=pyhd3eb1b0_0
  - colorama=0.4.6=py39haa95532_0
  - comm=0.2.1=py39haa95532_0
  - contourpy=1.2.0=py39h59b6b97_0
  - cryptography=43.0.0=py39h89fc84f_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - debugpy=1.6.7=py39hd77b12b_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - django=4.1=py39haa95532_0
  - docker-py=7.0.0=py39haa95532_0
  - et_xmlfile=1.1.0=py39haa95532_0
  - exceptiongroup=1.2.0=py39haa95532_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.6.3=h5da7b33_0
  - fiona=1.9.5=py39h4ed8f06_0
  - folium=0.14.0=py39haa95532_0
  - fontconfig=2.14.1=hb33846d_3
  - fonttools=4.51.0=py39h2bbff1b_0
  - freetype=2.12.1=ha860e81_0
  - freexl=2.0.0=hd7a5696_0
  - fuzzywuzzy=0.18.0=py39haa95532_0
  - gdal=3.6.2=py39h7670e6c_6
  - geographiclib=2.0=py39haa95532_0
  - geopandas=0.14.2=py39haa95532_0
  - geopandas-base=0.14.2=py39haa95532_0
  - geopy=2.4.1=py39haa95532_0
  - geos=3.8.0=h33f27b4_0
  - geotiff=1.7.0=h4545760_3
  - glib=2.78.4=hd77b12b_0
  - glib-tools=2.78.4=hd77b12b_0
  - hdf4=4.2.13=h712560f_2
  - hdf5=1.12.1=h51c971a_3
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.1=h6c2663c_0
  - idna=3.7=py39haa95532_0
  - importlib-metadata=7.0.1=py39haa95532_0
  - importlib_metadata=7.0.1=hd3eb1b0_0
  - importlib_resources=6.4.0=py39haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - ipykernel=6.29.5=py39haa95532_0
  - ipython=8.15.0=py39haa95532_0
  - jedi=0.19.1=py39haa95532_0
  - jinja2=3.1.4=py39haa95532_1
  - joblib=1.4.2=py39haa95532_0
  - jpeg=9e=h827c3e9_3
  - jupyter_client=8.6.0=py39haa95532_0
  - jupyter_core=5.7.2=py39haa95532_0
  - kealib=1.5.0=hde4a422_1
  - kiwisolver=1.4.4=py39hd77b12b_0
  - krb5=1.20.1=h5b6d351_0
  - lcms2=2.12=h83e58a3_0
  - lerc=3.0=hd77b12b_0
  - libboost=1.82.0=h3399ecb_2
  - libbrotlicommon=1.0.9=h2bbff1b_8
  - libbrotlidec=1.0.9=h2bbff1b_8
  - libbrotlienc=1.0.9=h2bbff1b_8
  - libclang=14.0.6=default_hb5a9fac_1
  - libclang13=14.0.6=default_h8e68704_1
  - libcurl=8.9.1=h0416ee5_0
  - libdeflate=1.17=h2bbff1b_1
  - libffi=3.4.4=hd77b12b_1
  - libgdal=3.6.2=h0e70117_6
  - libglib=2.78.4=ha17d25a_0
  - libiconv=1.16=h2bbff1b_3
  - libkml=1.3.0=h63940dd_7
  - libnetcdf=4.8.1=h6685c40_4
  - libpng=1.6.39=h8cc25b3_0
  - libpq=12.20=h70ee33d_0
  - libsodium=1.0.18=h62dcd97_0
  - libspatialindex=1.9.3=h6c2663c_0
  - libspatialite=5.1.0=h25d3e1c_1
  - libssh2=1.11.0=h291bd65_0
  - libtiff=4.5.1=hd77b12b_0
  - libwebp-base=1.3.2=h3d04722_1
  - libxml2=2.13.1=h24da03e_2
  - libzip=1.8.0=h289538f_1
  - lz4-c=1.9.4=h2bbff1b_1
  - mapclassify=2.5.0=py39haa95532_0
  - markupsafe=2.1.3=py39h2bbff1b_0
  - matplotlib=3.9.2=py39haa95532_0
  - matplotlib-base=3.9.2=py39he19b0ae_0
  - matplotlib-inline=0.1.6=py39haa95532_0
  - minizip=4.0.3=hb68bac4_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py39h2bbff1b_1
  - mkl_fft=1.3.11=py39h827c3e9_0
  - mkl_random=1.2.8=py39hc64d2fc_0
  - nest-asyncio=1.6.0=py39haa95532_0
  - networkx=3.2.1=py39haa95532_0
  - numexpr=2.10.1=py39h4cd664f_0
  - numpy=1.26.4=py39h055cbcc_0
  - numpy-base=1.26.4=py39h65a83cf_0
  - openjpeg=2.5.2=hae555c5_0
  - openpyxl=3.1.5=py39h827c3e9_0
  - openssl=3.0.15=h827c3e9_0
  - packaging=24.1=py39haa95532_0
  - pandas=2.2.2=py39h5da7b33_0
  - paramiko=2.8.1=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pcre2=10.42=h0ff8eda_1
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=10.4.0=py39h827c3e9_0
  - pip=24.2=py39haa95532_0
  - pixman=0.40.0=h2bbff1b_1
  - platformdirs=3.10.0=py39haa95532_0
  - ply=3.11=py39haa95532_0
  - poppler=22.12.0=h0bf3bde_3
  - poppler-data=0.4.11=haa95532_1
  - postgresql=12.20=h70ee33d_0
  - proj=9.3.1=ha107b6e_0
  - prompt-toolkit=3.0.43=py39haa95532_0
  - psutil=5.9.0=py39h2bbff1b_0
  - psycopg2=2.9.9=py39h2bbff1b_0
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pybind11-abi=5=hd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=py39haa95532_1
  - pynacl=1.5.0=py39h8cc25b3_0
  - pyparsing=3.1.2=py39haa95532_0
  - pyproj=3.6.1=py39h8d66fa9_0
  - pyqt=5.15.10=py39hd77b12b_0
  - pyqt5-sip=12.13.0=py39h2bbff1b_0
  - pysocks=1.7.1=py39haa95532_0
  - python=3.9.20=h8205438_1
  - python-dateutil=2.9.0post0=py39haa95532_2
  - python-levenshtein=0.12.2=py39h2bbff1b_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - pytz=2024.1=py39haa95532_0
  - pywin32=305=py39h2bbff1b_0
  - pyzmq=25.1.2=py39hd77b12b_0
  - qhull=2020.2=h59b6b97_2
  - qt-main=5.15.2=h19c9488_10
  - requests=2.32.3=py39haa95532_0
  - rtree=1.0.1=py39h2eaa2aa_0
  - scikit-learn=1.5.1=py39hc64d2fc_0
  - scipy=1.13.1=py39h8640f81_0
  - setuptools=75.1.0=py39haa95532_0
  - shapely=2.0.5=py39hd1cf0e4_0
  - sip=6.7.12=py39hd77b12b_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.45.3=h2bbff1b_0
  - sqlparse=0.4.4=py39haa95532_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tbb=2021.8.0=h59b6b97_0
  - threadpoolctl=3.5.0=py39h9909e9c_0
  - tiledb=2.3.3=hd8964de_3
  - tomli=2.0.1=py39haa95532_0
  - tornado=6.4.1=py39h827c3e9_0
  - tqdm=4.66.5=py39h9909e9c_0
  - traitlets=5.14.3=py39haa95532_0
  - typing_extensions=4.11.0=py39haa95532_0
  - tzdata=2024b=h04d1e81_0
  - unicodedata2=15.1.0=py39h2bbff1b_0
  - uriparser=0.9.7=h2bbff1b_0
  - urllib3=2.2.3=py39haa95532_0
  - vc=14.40=h2eaa2aa_1
  - vs2015_runtime=14.40.33807=h98bb1dd_1
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - websocket-client=1.8.0=py39haa95532_0
  - wheel=0.44.0=py39haa95532_0
  - win_inet_pton=1.1.0=py39haa95532_0
  - xerces-c=3.2.4=hd77b12b_1
  - xyzservices=2022.9.0=py39haa95532_1
  - xz=5.4.6=h8cc25b3_1
  - zeromq=4.3.5=hd77b12b_0
  - zipp=3.20.2=py39haa95532_0
  - zlib=1.2.13=h8cc25b3_1
  - zstd=1.5.6=h8880b57_0
  - pip:
      - dawg-python==0.7.2
      - docopt==0.6.2
      - future==1.0.0
      - geocoder==1.38.1
      - levenshtein==0.26.1
      - opencv-contrib-python==4.10.0.84
      - pymorphy2==0.9.1
      - pymorphy2-dicts-ru==2.4.417127.4579844
      - rapidfuzz==3.10.1
      - ratelim==0.1.6
      - rosreestr2coord==4.6.5
      - rutermextract==0.3
prefix: C:\Users\dukhno.vs\AppData\Local\anaconda3\envs\myenv
